### ISSUE TITLE
[FEATURE] 수강생목록으로 수강생 등록처리

### ISSUE THREAD

**Issue by ForestMS1** [2024-summer-project/AcademyManager_BE#104]
## 어떤 기능인가요?

수강생 추가/제거 api대신

수강생목록을 받아서 그상태 고대로 수강생등록을 처리

## 작업 상세 내용

- [x] 수강생목록을 전달받아서 그 목록 그대로 수강생등록처리함.

## 참고할만한 자료(선택)

![image](https://github.com/user-attachments/assets/04dc1064-f291-4649-aa6b-59c1ded4b72f)

**Comment by SunwooKim11** [comment]
API 실행시 아래의 에러가 발생하게 됩니다. LectureParticipant의 create, delete 까지 정상정으로 되나, 그 다음 count 연산에서 에러가 발생합니다. 코드에서 lecture_id가 잘못들어가 있습니다. target_id가 아닌 targetLectureId가 들어가야 정상 작동하기에 이를 수정합니다.
![image](https://github.com/user-attachments/assets/debf8b4f-eb51-44a2-b469-503b9e07f9ac)

```code
 const participantCount = await prisma.LectureParticipant.count({
      where: {
        lecture_id: target_id,
      },
    });
