### ISSUE TITLE
[FEATURE] 로그인,로그아웃API

### ISSUE THREAD

**Issue by ForestMS1** [2024-summer-project/AcademyManager_BE#4]
## 어떤 기능인가요?

> 로그인, 로그아웃API 개발

## 작업 상세 내용

- [x] 로그인API
- [x] 로그아웃API

## 참고할만한 자료(선택)
![image](https://github.com/user-attachments/assets/170b8e32-4bb0-4c0f-8dbb-e29b3693a947)

**Comment by ForestMS1** [comment]
feat: passport,bcrypt 라이브러리 추가, 로그인API 구현
9e9c348b6608208c5f9ebf5017fecee0e13a9fb7
제 컴퓨터에서 port번호 5000이 사용불가라 8000으로 바꿨는데 깜빡하고 안돌려놨네욤..^^;;

**Comment by SunwooKim11** [comment]
feat: passport,bcrypt 라이브러리 추가, 로그인API 구현 - 9e9c348
세션 인증방식으로 구현하셨군요. 수고하셨습니다. logout api는 제가 만들게요!
