### ISSUE TITLE
[FEATURE] Lecture 모델에 수업요일, 수업시간을 추가

### ISSUE THREAD

**Issue by ForestMS1** [2024-summer-project/AcademyManager_BE#70]
## 어떤 기능인가요?

>출석, 시간표(모바일) 기능을 위해 Lecture 모델에 수업요일, 수업시간을 추가합니다.

## 작업 상세 내용
Lecture 모델에 수업요일, 수업시간을 추가하고 그와 관련된 API들을 수정합니다.

- [x] schema에서 Lecture에 수업요일, 수업시간 추가
- [x] 에브리타임처럼 여러요일 받을 수 있게
- [x] 에브리타임처럼 수업시작시간~끝시간
- [x] 과목생성, 과목조회, 과목수정 API 수업요일, 수업시간 추가
- [x] 학생 수강 강의 리스트 조회 API 응답에 수업요일, 수업시간 추가

**Comment by SunwooKim11** [comment]
swagger 테스트 중 에러가 있어 수정하기위해 재오픈했습니다
-> 수정 완료헀습니다.
