### ISSUE TITLE
[FEATURE] swagger API 문서 자동화하기

### ISSUE THREAD

**Issue by ForestMS1** [2024-summer-project/AcademyManager_BE#75]
## 어떤 기능인가요?

API 명세서 작성, 수정하기 너무 귀찮고 힘들어서 swagger로 API 문서 자동화 해보려고 합니다.

## 작업 상세 내용

- [x] swagger세팅
- [x] Router.js파일들 swagger 주석추가
- [x] TODO

## 참고할만한 자료(선택)
autogen 사용해서 주석 자동추가를 사용해봤는데 완벽하게 만들어주지 않네요😨

그래서 선우님 말씀대로 gpt한테 API코드 보여주고 swagger주석 만들어 달라고하니 훨 나은거같습니다.

아래는 userRouter만 swagger주석 만들어본 사진입니다.
![image](https://github.com/user-attachments/assets/96586294-2589-49d8-839a-2b7dd06c93a4)
![image](https://github.com/user-attachments/assets/a4fe1e73-ca05-4ddd-972e-ba2ae7e1d826)
![image](https://github.com/user-attachments/assets/8c27d4f9-6f8c-4ebd-9d7f-4dd85c60b9e1)

**Comment by SunwooKim11** [comment]
오,, 깔끔하게 잘된거 같은데요? 다른것도 다 GPT 돌릴까요 그러면

**Comment by ForestMS1** [comment]
좋습니다 그러면 선우님이 lectureRouter.js랑 registrationRouter.js의 해당 API코드들 gpt돌려주세요 API 코드 돌리기 전에 Router파일을 gpt한테 보여주면 좋을 것 같습니다.

**Comment by ForestMS1** [comment]
아니다 제가 천천히 돌릴게요

**Comment by SunwooKim11** [comment]
제가해도 되는데,, 알겠습니다 ㅜ.ㅜ

**Comment by ForestMS1** [comment]
아 그러면 부탁드립니다 ㅎㅎ 생각해보니 좀 오래걸릴거같네요 ㅋㅋㅋ
