### ISSUE TITLE
[FIX] My과목 시험종류별 성적 조회API 수정

### ISSUE THREAD

**Issue by ForestMS1** [2024-summer-project/AcademyManager_BE#78]
## 어떤 기능인가요?

>My과목 시험종류별 성적 조회API 수정
- 학생이 시험을 응시하지 않았을 시, 시험 점수를 리턴 안하게 수정(null 값 안넘기기)
- param이름을 exam_type에서 exam_type_id로 수정 
## 작업 상세 내용

- [x] TODO
- [x] TODO
- [x] TODO

**Comment by SunwooKim11** [comment]
이거 이미 둘 다 주고 있어서 수정할필요는 없고, 제가 이 함수 코드 리팩토링만 할게요!(변수 수정, 점수 null 일시 미반환)
